export const samplePgn = [
  {
    id: 0,
    moveFrom: 'd2',
    moveTo: 'd4',
    fen: 'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR',
    isBestMoment: true,
    comment: 'For those that know me, I play 1. d4 almost exclusively.',
  },
  {
    id: 1,
    moveFrom: 'e7',
    moveTo: 'e6',
    fen: 'rnbqkbnr/pppp1ppp/4p3/8/3P4/8/PPP1PPPP/RNBQKBNR',
    isBestMoment: true,
    comment:
      "It is responses like this that drive me crazy. I'm pretty solid in most variations of the QGD and QGA, and black's response just took away my comfort zone.",
  },
  {
    id: 2,
    moveFrom: 'e2',
    moveTo: 'e4',
    fen: 'rnbqkbnr/pppp1ppp/4p3/8/3PP3/8/PPP2PPP/RNBQKBNR',
    isBestMoment: false,
    comment: "If he's giving, I'm taking.....",
  },
  {
    id: 3,
    moveFrom: 'g8',
    moveTo: 'f6',
    fen: 'rnbqkb1r/pppp1ppp/4pn2/8/3PP3/8/PPP2PPP/RNBQKBNR',
    isBestMoment: true,
    comment: '',
  },
  {
    id: 4,
    moveFrom: 'c1',
    moveTo: 'g5',
    fen: 'rnbqkb1r/pppp1ppp/4pn2/6B1/3PP3/8/PPP2PPP/RN1QKBNR',
    isBestMoment: true,
    comment: 'I had numerous alternatives here, but decided to start the tactics early.',
  },
  {
    id: 5,
    moveFrom: 'h7',
    moveTo: 'h6',
    fen: 'rnbqkb1r/pppp1pp1/4pn1p/6B1/3PP3/8/PPP2PPP/RN1QKBNR',
    isBestMoment: false,
    comment: 'Attempting to drive the bishop back.',
  },
];
